version: '3'
services:

  appnode:
    container_name: food_court_appnode
    restart: always
    build: ./dark/
    ports:
      - "80:80"
    networks:
      - foodcounrtnet
    environment:
      MYSQL_HOST_PORT: "food_court_storage:3306"
      MYSQL_USER: "appuser1"
      MYSQL_PASSWORD: "secretpwd1"
      MYSQL_DB: "food_court"

  mysql:
    container_name: food_court_storage
    restart: always
    build: ./storage/
    ports:
      - "3307:3306"
    networks:
      - foodcounrtnet
    environment:
      MYSQL_ROOT_PASSWORD: "root"

networks:
  foodcounrtnet:
