INSERT INTO `food_court`.`User` (`id`, `enabled`, `password`, `username`) VALUES (0, 1, 'root', 'root');
INSERT INTO `food_court`.`User` (`id`, `enabled`, `password`, `username`) VALUES (0, 1, 'pwd1', 'user1');
INSERT INTO `food_court`.`User` (`id`, `enabled`, `password`, `username`) VALUES (0, 1, 'pwd2', 'user2');
INSERT INTO `food_court`.`UserRole` (`id`, `name`) VALUES (0, 'ROLE_ADMIN');
INSERT INTO `food_court`.`UserRole` (`id`, `name`) VALUES (0, 'ROLE_USER');
INSERT INTO `food_court`.`UserRole` (`id`, `name`) VALUES (0, 'ROLE_TESTER');
INSERT INTO `food_court`.`User_UserRole` (`User_id`, `roles_id`) VALUES (1, 1);
INSERT INTO `food_court`.`User_UserRole` (`User_id`, `roles_id`) VALUES (2, 1);
INSERT INTO `food_court`.`User_UserRole` (`User_id`, `roles_id`) VALUES (2, 2);
INSERT INTO `food_court`.`User_UserRole` (`User_id`, `roles_id`) VALUES (3, 2);
