
export const TEXT = {
    ORDER_CONFIRMATION_APPROVE: "отправить",
    REJECT_ORDER: "отмена заказа",
    GO_BACK: "назад",
    STEPPER_STAGE_1: "Ваше имя",
    STEPPER_STAGE_2: "Пирожное/Булка",
    STEPPER_STAGE_3: "Количество",
    STEPPER_STAGE_4: "Подтверждение",
    HELPER_STAGE_1: "Выберите первую букву вашей фамилии",
    HELPER_STAGE_2: "Как вас зовут",
    HELPER_STAGE_3: "Выберите изделие",
    HELPER_STAGE_4: "Выберите количество",
    HELPER_STAGE_5: "Завершите выбор",
    EDITOR_TITLE_CREATE: "Создать",
    EDITOR_TITLE_UPDATE: "Изменить",
    EDITOR_TITLE_ACTIONS: "Действия",
    EDITOR_ACTION_SAVE: "сохранить",
    EDITOR_ACTION_CANCEL: "отмена",
    EDITOR_CUSTOMER_NAME: "Имя",
    EDITOR_CUSTOMER_EMAIL: "EMail",
    EDITOR_CUSTOMER_BALANCE: "Баланс",
    EDITOR_CUSTOMER_ACTION_REFILL: "Пополнить",
    EDITOR_CUSTOMER_ACTION_REFILL_1000: "Пополнить на 1000 ₽",
    EDITOR_CAKE_NAME: "Имя",
    EDITOR_CAKE_EMAIL: "Цена",
    LOGOUT: "выход",
    MANAGER_MENU_TITLE_ORDERS: "Заказы",
    MANAGER_MENU_TITLE_INCOMING: "Пополнение",
    MANAGER_MENU_TITLE_CAKES: "Пирожные/Булки",
    MANAGER_MENU_TITLE_CUSTOMERS: "Покупатели",
    LOADING: "загрузка...",
    TABLE_VIEW_MSG_EMPTY: "нет данных для отображения",
    TABLE_VIEW_PREV_PAGE: "предыдущая страница",
    TABLE_VIEW_NEXT_PAGE: "следующая страница",
    TABLE_VIEW_SEARCH_CLEAR: "Очистить поиск",
    TABLE_VIEW_REFRESH: "Обновить",
    LOGIN_FORM_TITLE: "WILEY",
    LOGIN_FORM_FIELD_LOGIN: "логин",
    LOGIN_FORM_FIELD_PWD: "пароль",
    LOGIN_FORM_ACTION_LOGIN: "войти",
    DATA_ENTITY_CAKE_NAME: "Название",
    DATA_ENTITY_CAKE_PRICE: "Цена",
    DATA_ENTITY_CAKE_AVAILABLE: "Доступность",
    DATA_ENTITY_CAKE_VERSION: "Версия",
    DATA_ENTITY_CUSTOMER_NAME: "Имя",
    DATA_ENTITY_CUSTOMER_EMAIL: "Email",
    DATA_ENTITY_CUSTOMER_BALANCE: "Баланс",
    DATA_ENTITY_INCOMING_TIME: "Время",
    DATA_ENTITY_INCOMING_CUSTOMER: "Покупатель",
    DATA_ENTITY_INCOMING_AMOUNT: "Сумма",
    DATA_ENTITY_INCOMING_BALANCE: "Баланс",
    DATA_ENTITY_ORDER_TIME: "Время",
    DATA_ENTITY_ORDER_ORDER_PRICE: "Сумма заказа",
    DATA_ENTITY_ORDER_COUNT: "Количество",
    DATA_ENTITY_ORDER_CUSTOMER: "Покупатель",
    DATA_ENTITY_ORDER_CAKE: "Пирожное/Булка",
    DATA_ENTITY_ORDER_CAKE_PRICE: "Цена",
    UNABLE_TO_LOGIN: "Невозможно войти, проверьте логин/пароль и попробуйте еще раз",
};
