GET http://localhost/groups

###

GET http://localhost/groups/7

###

GET http://localhost/groups/2/customers

###

GET http://localhost/customers?page=0&limit=3&orderBy=balance

###

GET http://localhost/cakes

###

GET http://localhost/cakes/10

###

GET http://localhost/customers/2

###
