GET http://localhost/api/groups

###

GET http://localhost/api/groups/7

###

GET http://localhost/api/groups/2/customers

###

GET http://localhost/api/customers?page=0&limit=3&orderBy=balance

###

GET http://localhost/api/customers?page=0&limit=3&search=rebe

###

GET http://localhost/api/cakes

###

GET http://localhost/api/cakes/10

###

GET http://localhost/api/customers/2

###
