
GET http://{{host}}:{{port}}/orders
Cookie: JSESSIONID={{authcookie}}

###

GET http://{{host}}:{{port}}/orders/234
Cookie: JSESSIONID={{authcookie}}

###

PUT http://{{host}}:{{port}}/orders
Cookie: JSESSIONID={{authcookie}}
Content-Type: application/json

{"customer": 1, "cake": 5, "count": 77}

###
